# Generated by Django 4.0.6 on 2022-07-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
