# Generated by Django 4.0.6 on 2022-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='images/profile')),
                ('cover', models.ImageField(upload_to='images/cover')),
            ],
        ),
    ]
