# Generated by Django 4.0.6 on 2022-07-15 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_fotosperfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FotosPerfil',
        ),
    ]
