# Generated by Django 4.0.6 on 2022-07-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_comentario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='postagem',
        ),
        migrations.AddField(
            model_name='post',
            name='comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.comentario'),
        ),
    ]
