# Generated by Django 4.0.6 on 2022-07-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_remove_post_comentario_comentario_postagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='postagem',
            new_name='id_post',
        ),
    ]
