# Generated by Django 4.0.6 on 2022-07-15 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_delete_fotosperfil'),
        ('post', '0014_rename_postagem_comentario_id_post'),
    ]

    operations = [
    ]
