# Generated by Django 4.0.6 on 2022-07-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0020_remove_profile_datalogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='capa',
            field=models.URLField(null=True),
        ),
    ]
