# Generated by Django 4.0.6 on 2022-07-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_profile_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
