name: Django CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_DB: db_twitter
          POSTGRES_USER: lucas_db
          POSTGRES_PASSWORD: luke93
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 55432
        ports: [ '55432:5432' ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Instalar dependências
      run: |
        pip install -r requirements-dev.txt
    - name: Lint com Flake8
      run: |
        flake8
    - name: Copiando arquivo de configuração
      run: |
        cp .env-sample .env
    - name: Testes de aplicação com Pytest
      run: |
        pytest --cov
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: eb1e36c2-4d11-40ca-b617-3b02429a6c38
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage1.xml,./coverage2.xml
        flags: unittests
        name: codecov-umbrella
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true